vim.keymap.set("n", ",", ";", { noremap = true })
vim.keymap.set("n", ";", ",", { noremap = true })
vim.keymap.set({ "n", "v" }, "<S-J>", "Lzz", { noremap = true })
vim.keymap.set({ "n", "v" }, "<S-K>", "Hzz", { noremap = true })
vim.keymap.set("t", "<Esc>", [[<C-\><C-n>]])
vim.keymap.set("n", "ä", "@")
